### ISSUE TITLE
consider different cli structure && auto generated docs

### ISSUE THREAD

**Issue by bukowa** [pojntfx/liwasc#1]
Hey what do you think about implementing cli package structure like in this project https://github.com/bukowa/go-cobra-example

That would make it easier to reuse and bind frontend and backend into one CLI. Also the auto-generated docs look cool.
I wish i could make a pull request but i don't have a chance to dive deeply into the code making sure everything works so it's just a suggestion.

**Comment by pojntfx** [comment]
Hey :) Thanks for the suggestion, but I don't intent to change the project structure in the future - it's simply the default I use in Go-based projects. If one wants to compose their own CLI based on liwasc, they may embed from `pkg` - the API is quite simple. The auto-generated docs are indeed nice, but as this project uses only one `cmd`, I believe https://github.com/pojntfx/liwasc#command-line-arguments to be sufficient and easier to maintain for now.
